<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Dapatkan kategori yang sudah ada
        $categories = Category::all()->pluck('id', 'slug');

        $products = [
            // ALAT KESEHATAN UMUM (15 produk)
            [
                'category_id' => $categories['alat-kesehatan-umum'],
                'name' => 'Tensimeter Digital Omron HEM-7120',
                'slug' => 'tensimeter-digital-omron-hem-7120',
                'description' => 'Tensimeter digital otomatis dengan akurasi tinggi, layar LCD besar, dan teknologi Intellisense untuk pengukuran yang nyaman.',
                'image' => 'https://images.unsplash.com/photo-1615461066841-6116e61058f4?w=500&h=500&fit=crop',
                'sku' => 'TEN-001',
                'price' => 450000,
                'discount_price' => 399000,
                'stock' => 75,
                'unit' => 'pcs',
                'brand' => 'Omron',
                'is_featured' => true,
            ],
            [
                'category_id' => $categories['alat-kesehatan-umum'],
                'name' => 'Thermometer Digital Infrared Non-Contact',
                'slug' => 'thermometer-digital-infrared-non-contact',
                'description' => 'Thermometer infrared tanpa sentuh, hasil cepat 1 detik, cocok untuk bayi dan dewasa, dengan memory penyimpanan 32 data.',
                'image' => 'https://images.unsplash.com/photo-1584820927498-cfe5211fd8bf?w=500&h=500&fit=crop',
                'sku' => 'THER-001',
                'price' => 185000,
                'discount_price' => 165000,
                'stock' => 120,
                'unit' => 'pcs',
                'brand' => 'Beurer',
                'is_featured' => true,
            ],
            [
                'category_id' => $categories['alat-kesehatan-umum'],
                'name' => 'Nebulizer Compressor Omron NE-C28',
                'slug' => 'nebulizer-compressor-omron-ne-c28',
                'description' => 'Nebulizer kompresor untuk terapi pernapasan, teknologi V.V.T untuk efisiensi obat maksimal, cocok untuk asma dan COPD.',
                'image' => 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=500&h=500&fit=crop',
                'sku' => 'NEB-001',
                'price' => 650000,
                'discount_price' => 599000,
                'stock' => 45,
                'unit' => 'pcs',
                'brand' => 'Omron',
                'is_featured' => true,
            ],
            [
                'category_id' => $categories['alat-kesehatan-umum'],
                'name' => 'Pulse Oximeter Fingertip',
                'slug' => 'pulse-oximeter-fingertip',
                'description' => 'Alat pengukur kadar oksigen dalam darah (SpO2) dan detak jantung, layar OLED, portable dan akurat.',
                'image' => 'https://images.unsplash.com/photo-1615461065624-c9b99c9cd69c?w=500&h=500&fit=crop',
                'sku' => 'OXI-001',
                'price' => 175000,
                'stock' => 90,
                'unit' => 'pcs',
                'brand' => 'Beurer',
            ],
            [
                'category_id' => $categories['alat-kesehatan-umum'],
                'name' => 'Timbangan Badan Digital',
                'slug' => 'timbangan-badan-digital',
                'description' => 'Timbangan digital dengan kapasitas 180kg, layar LCD besar, auto-on/off, akurasi 100g.',
                'image' => 'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=500&h=500&fit=crop',
                'sku' => 'SCALE-001',
                'price' => 125000,
                'stock' => 65,
                'unit' => 'pcs',
                'brand' => 'OneMed',
            ],
            [
                'category_id' => $categories['alat-kesehatan-umum'],
                'name' => 'Alat Tes Gula Darah GlucoDr AGM-2100',
                'slug' => 'alat-tes-gula-darah-glucodr-agm-2100',
                'description' => 'Alat cek gula darah digital, hasil cepat 5 detik, memory 450 data, strip test ekonomis.',
                'image' => 'https://images.unsplash.com/photo-1615461066841-6116e61058f4?w=500&h=500&fit=crop',
                'sku' => 'GLUCO-001',
                'price' => 250000,
                'discount_price' => 225000,
                'stock' => 55,
                'unit' => 'pcs',
                'brand' => 'GlucoDr',
            ],
            [
                'category_id' => $categories['alat-kesehatan-umum'],
                'name' => 'Stetoskop Littmann Classic III',
                'slug' => 'stetoskop-littmann-classic-iii',
                'description' => 'Stetoskop profesional dual head, akustik superior, ideal untuk dokter umum dan spesialis.',
                'image' => 'https://images.unsplash.com/photo-1631815589968-fdb09a223b1e?w=500&h=500&fit=crop',
                'sku' => 'STETH-001',
                'price' => 2500000,
                'stock' => 30,
                'unit' => 'pcs',
                'brand' => '3M Littmann',
                'is_featured' => true,
            ],
            [
                'category_id' => $categories['alat-kesehatan-umum'],
                'name' => 'Alat Uap Facial Steamer',
                'slug' => 'alat-uap-facial-steamer',
                'description' => 'Alat uap wajah untuk membuka pori-pori, membersihkan kulit, dan terapi aromaterapi.',
                'image' => 'https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=500&h=500&fit=crop',
                'sku' => 'STEAM-001',
                'price' => 280000,
                'discount_price' => 249000,
                'stock' => 40,
                'unit' => 'pcs',
                'brand' => 'Beurer',
            ],
            [
                'category_id' => $categories['alat-kesehatan-umum'],
                'name' => 'Bantalan Pemanas Listrik',
                'slug' => 'bantalan-pemanas-listrik',
                'description' => 'Heating pad untuk meredakan nyeri otot, 3 level suhu, auto shut-off safety, ukuran 30x40cm.',
                'image' => 'https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?w=500&h=500&fit=crop',
                'sku' => 'HEAT-001',
                'price' => 195000,
                'stock' => 50,
                'unit' => 'pcs',
                'brand' => 'Beurer',
            ],
            [
                'category_id' => $categories['alat-kesehatan-umum'],
                'name' => 'Alat Pijat Elektrik Portabel',
                'slug' => 'alat-pijat-elektrik-portabel',
                'description' => 'Massager elektrik dengan 4 head pijat, 20 mode, intensitas adjustable, rechargeable battery.',
                'image' => 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=500&h=500&fit=crop',
                'sku' => 'MASS-001',
                'price' => 320000,
                'stock' => 45,
                'unit' => 'pcs',
                'brand' => 'Xiaomi',
            ],
            [
                'category_id' => $categories['alat-kesehatan-umum'],
                'name' => 'Kacamata Terapi Minus',
                'slug' => 'kacamata-terapi-minus',
                'description' => 'Kacamata pinhole therapy untuk melatih otot mata, mengurangi minus, aman untuk semua usia.',
                'image' => 'https://images.unsplash.com/photo-1574258495973-f010dfbb5371?w=500&h=500&fit=crop',
                'sku' => 'GLASS-001',
                'price' => 65000,
                'stock' => 100,
                'unit' => 'pcs',
                'brand' => 'Generic',
            ],
            [
                'category_id' => $categories['alat-kesehatan-umum'],
                'name' => 'Tensimeter Aneroid Manual',
                'slug' => 'tensimeter-aneroid-manual',
                'description' => 'Tensimeter manual profesional dengan stetoskop, akurat dan tahan lama, untuk tenaga medis.',
                'image' => 'https://images.unsplash.com/photo-1615461066841-6116e61058f4?w=500&h=500&fit=crop',
                'sku' => 'TEN-002',
                'price' => 175000,
                'stock' => 60,
                'unit' => 'pcs',
                'brand' => 'OneMed',
            ],
            [
                'category_id' => $categories['alat-kesehatan-umum'],
                'name' => 'Alat Tes Kehamilan Digital',
                'slug' => 'alat-tes-kehamilan-digital',
                'description' => 'Test pack digital dengan layar LCD, akurasi 99%, hasil jelas pregnant/not pregnant, early detection.',
                'image' => 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=500&h=500&fit=crop',
                'sku' => 'PREG-001',
                'price' => 45000,
                'stock' => 150,
                'unit' => 'pcs',
                'brand' => 'Clearblue',
            ],
            [
                'category_id' => $categories['alat-kesehatan-umum'],
                'name' => 'Ear Thermometer Braun',
                'slug' => 'ear-thermometer-braun',
                'description' => 'Thermometer telinga infrared profesional, teknologi pre-warmed tip, akurasi tinggi, hasil 1 detik.',
                'image' => 'https://images.unsplash.com/photo-1584820927498-cfe5211fd8bf?w=500&h=500&fit=crop',
                'sku' => 'THER-002',
                'price' => 650000,
                'stock' => 35,
                'unit' => 'pcs',
                'brand' => 'Braun',
            ],
            [
                'category_id' => $categories['alat-kesehatan-umum'],
                'name' => 'Body Fat Monitor Digital',
                'slug' => 'body-fat-monitor-digital',
                'description' => 'Alat ukur lemak tubuh, BMI, massa otot, dan air tubuh, Bluetooth connect to smartphone app.',
                'image' => 'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=500&h=500&fit=crop',
                'sku' => 'FAT-001',
                'price' => 380000,
                'discount_price' => 349000,
                'stock' => 40,
                'unit' => 'pcs',
                'brand' => 'Omron',
            ],

            // ALAT MEDIS (15 produk)
            [
                'category_id' => $categories['alat-medis'],
                'name' => 'Masker Medis 3 Ply Disposable (50 pcs)',
                'slug' => 'masker-medis-3-ply-disposable-50-pcs',
                'description' => 'Masker medis 3 lapis sekali pakai, filter bakteri 98%, earloop lembut, tidak iritasi.',
                'image' => 'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=500&h=500&fit=crop',
                'sku' => 'MASK-001',
                'price' => 35000,
                'discount_price' => 29000,
                'stock' => 500,
                'unit' => 'box',
                'brand' => 'Sensi',
                'is_featured' => true,
            ],
            [
                'category_id' => $categories['alat-medis'],
                'name' => 'Masker N95 FFP2 (10 pcs)',
                'slug' => 'masker-n95-ffp2-10-pcs',
                'description' => 'Masker N95 standar medis, filter 95% partikel, adjustable nose clip, certified.',
                'image' => 'https://images.unsplash.com/photo-1603796846097-bee99e4a601f?w=500&h=500&fit=crop',
                'sku' => 'MASK-002',
                'price' => 125000,
                'stock' => 200,
                'unit' => 'box',
                'brand' => '3M',
            ],
            [
                'category_id' => $categories['alat-medis'],
                'name' => 'Sarung Tangan Latex Steril',
                'slug' => 'sarung-tangan-latex-steril',
                'description' => 'Gloves latex steril untuk tindakan medis, powder-free, hypoallergenic, size M (isi 100 pcs).',
                'image' => 'https://images.unsplash.com/photo-1584744982493-457e7a46d0d4?w=500&h=500&fit=crop',
                'sku' => 'GLOVE-001',
                'price' => 85000,
                'stock' => 300,
                'unit' => 'box',
                'brand' => 'OneMed',
            ],
            [
                'category_id' => $categories['alat-medis'],
                'name' => 'Hand Sanitizer Gel 500ml',
                'slug' => 'hand-sanitizer-gel-500ml',
                'description' => 'Hand sanitizer dengan alkohol 70%, membunuh 99.9% kuman, tidak lengket, aroma fresh.',
                'image' => 'https://images.unsplash.com/photo-1584744982493-457e7a46d0d4?w=500&h=500&fit=crop',
                'sku' => 'SANI-001',
                'price' => 35000,
                'stock' => 250,
                'unit' => 'botol',
                'brand' => 'Antis',
            ],
            [
                'category_id' => $categories['alat-medis'],
                'name' => 'Plester Luka Waterproof (100 pcs)',
                'slug' => 'plester-luka-waterproof-100-pcs',
                'description' => 'Plester luka tahan air, berbagai ukuran, hypoallergenic, breathable, tidak lengket di luka.',
                'image' => 'https://images.unsplash.com/photo-1603883359806-e84a4f285f93?w=500&h=500&fit=crop',
                'sku' => 'BAND-001',
                'price' => 25000,
                'stock' => 180,
                'unit' => 'box',
                'brand' => 'Hansaplast',
            ],
            [
                'category_id' => $categories['alat-medis'],
                'name' => 'Alkohol 70% 1 Liter',
                'slug' => 'alkohol-70-1-liter',
                'description' => 'Alkohol antiseptik 70% untuk membersihkan luka dan sterilisasi alat medis.',
                'image' => 'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=500&h=500&fit=crop',
                'sku' => 'ALC-001',
                'price' => 28000,
                'stock' => 150,
                'unit' => 'botol',
                'brand' => 'OneMed',
            ],
            [
                'category_id' => $categories['alat-medis'],
                'name' => 'Kasa Steril 16x16 cm (10 pcs)',
                'slug' => 'kasa-steril-16x16-cm-10-pcs',
                'description' => 'Kasa steril untuk perawatan luka, menyerap cairan, lembut dan tidak menempel di luka.',
                'image' => 'https://images.unsplash.com/photo-1603883359806-e84a4f285f93?w=500&h=500&fit=crop',
                'sku' => 'GAUZE-001',
                'price' => 15000,
                'stock' => 220,
                'unit' => 'pack',
                'brand' => 'OneMed',
            ],
            [
                'category_id' => $categories['alat-medis'],
                'name' => 'Perban Elastis 10cm x 4.5m',
                'slug' => 'perban-elastis-10cm-x-45m',
                'description' => 'Perban elastis untuk fiksasi, kompresi, dan support, breathable dan nyaman.',
                'image' => 'https://images.unsplash.com/photo-1603883359806-e84a4f285f93?w=500&h=500&fit=crop',
                'sku' => 'BANDAGE-001',
                'price' => 18000,
                'stock' => 160,
                'unit' => 'roll',
                'brand' => 'Hypafix',
            ],
            [
                'category_id' => $categories['alat-medis'],
                'name' => 'Jarum Suntik 3ml Disposable (100 pcs)',
                'slug' => 'jarum-suntik-3ml-disposable-100-pcs',
                'description' => 'Syringe 3ml sekali pakai dengan jarum 23G, steril, untuk injeksi intramuskular dan subkutan.',
                'image' => 'https://images.unsplash.com/photo-1631815589968-fdb09a223b1e?w=500&h=500&fit=crop',
                'sku' => 'SYRINGE-001',
                'price' => 120000,
                'stock' => 80,
                'unit' => 'box',
                'brand' => 'Terumo',
            ],
            [
                'category_id' => $categories['alat-medis'],
                'name' => 'Infus Set Disposable (50 pcs)',
                'slug' => 'infus-set-disposable-50-pcs',
                'description' => 'Set infus sekali pakai lengkap dengan selang dan regulator, steril, kualitas medis.',
                'image' => 'https://images.unsplash.com/photo-1631815589968-fdb09a223b1e?w=500&h=500&fit=crop',
                'sku' => 'INFUS-001',
                'price' => 85000,
                'stock' => 100,
                'unit' => 'box',
                'brand' => 'OneMed',
            ],
            [
                'category_id' => $categories['alat-medis'],
                'name' => 'Kateter Urine Foley Catheter No.16',
                'slug' => 'kateter-urine-foley-catheter-no16',
                'description' => 'Kateter urine 2-way silicon, steril, untuk drainase urine jangka panjang.',
                'image' => 'https://images.unsplash.com/photo-1631815589968-fdb09a223b1e?w=500&h=500&fit=crop',
                'sku' => 'CATH-001',
                'price' => 15000,
                'stock' => 120,
                'unit' => 'pcs',
                'brand' => 'Rusch',
            ],
            [
                'category_id' => $categories['alat-medis'],
                'name' => 'Scalpel Blade Pisau Bedah No.15',
                'slug' => 'scalpel-blade-pisau-bedah-no15',
                'description' => 'Mata pisau bedah no.15 steril, tajam, untuk insisi bedah minor, isi 100 pcs.',
                'image' => 'https://images.unsplash.com/photo-1631815589968-fdb09a223b1e?w=500&h=500&fit=crop',
                'sku' => 'SCALPEL-001',
                'price' => 75000,
                'stock' => 60,
                'unit' => 'box',
                'brand' => 'Swann-Morton',
            ],
            [
                'category_id' => $categories['alat-medis'],
                'name' => 'Gunting Bedah Stainless Steel',
                'slug' => 'gunting-bedah-stainless-steel',
                'description' => 'Gunting surgical stainless steel, tajam dan tahan karat, untuk tindakan medis.',
                'image' => 'https://images.unsplash.com/photo-1631815589968-fdb09a223b1e?w=500&h=500&fit=crop',
                'sku' => 'SCISSORS-001',
                'price' => 45000,
                'stock' => 70,
                'unit' => 'pcs',
                'brand' => 'OneMed',
            ],
            [
                'category_id' => $categories['alat-medis'],
                'name' => 'Pinset Anatomis 14cm',
                'slug' => 'pinset-anatomis-14cm',
                'description' => 'Pinset anatomis stainless steel untuk holding tissue, ujung rata, autoclavable.',
                'image' => 'https://images.unsplash.com/photo-1631815589968-fdb09a223b1e?w=500&h=500&fit=crop',
                'sku' => 'PINSET-001',
                'price' => 25000,
                'stock' => 90,
                'unit' => 'pcs',
                'brand' => 'OneMed',
            ],
            [
                'category_id' => $categories['alat-medis'],
                'name' => 'Tourniquet Tali Pembendung',
                'slug' => 'tourniquet-tali-pembendung',
                'description' => 'Tourniquet latex untuk pembendungan pembuluh darah saat pengambilan darah.',
                'image' => 'https://images.unsplash.com/photo-1631815589968-fdb09a223b1e?w=500&h=500&fit=crop',
                'sku' => 'TOUR-001',
                'price' => 8000,
                'stock' => 200,
                'unit' => 'pcs',
                'brand' => 'Generic',
            ],

            // SUPLEMEN & VITAMIN (12 produk)
            [
                'category_id' => $categories['suplemen-vitamin'],
                'name' => 'Blackmores Vitamin C 1000mg (150 tablets)',
                'slug' => 'blackmores-vitamin-c-1000mg-150-tablets',
                'description' => 'Vitamin C dosis tinggi untuk meningkatkan daya tahan tubuh, antioksidan kuat, reduces severity of common cold.',
                'image' => 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&h=500&fit=crop',
                'sku' => 'VIT-001',
                'price' => 285000,
                'discount_price' => 259000,
                'stock' => 180,
                'unit' => 'botol',
                'brand' => 'Blackmores',
                'is_featured' => true,
            ],
            [
                'category_id' => $categories['suplemen-vitamin'],
                'name' => 'Blackmores Omega 3 Fish Oil 1000mg',
                'slug' => 'blackmores-omega-3-fish-oil-1000mg',
                'description' => 'Omega 3 dari minyak ikan untuk kesehatan jantung, otak, dan mata, odourless capsules.',
                'image' => 'https://images.unsplash.com/photo-1550572017-edd951aa8cae?w=500&h=500&fit=crop',
                'sku' => 'VIT-002',
                'price' => 320000,
                'discount_price' => 289000,
                'stock' => 150,
                'unit' => 'botol',
                'brand' => 'Blackmores',
                'is_featured' => true,
            ],
            [
                'category_id' => $categories['suplemen-vitamin'],
                'name' => 'Nature\'s Plus Ultra Hair Plus',
                'slug' => 'natures-plus-ultra-hair-plus',
                'description' => 'Suplemen untuk kesehatan rambut, kuku, dan kulit dengan biotin, MSM, dan amino acids.',
                'image' => 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&h=500&fit=crop',
                'sku' => 'VIT-003',
                'price' => 450000,
                'stock' => 80,
                'unit' => 'botol',
                'brand' => 'Nature\'s Plus',
            ],
            [
                'category_id' => $categories['suplemen-vitamin'],
                'name' => 'Wellness Excell-C 500mg',
                'slug' => 'wellness-excell-c-500mg',
                'description' => 'Vitamin C 500mg dengan bioflavonoid untuk meningkatkan imunitas, antioksidan.',
                'image' => 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&h=500&fit=crop',
                'sku' => 'VIT-004',
                'price' => 95000,
                'stock' => 200,
                'unit' => 'botol',
                'brand' => 'Wellness',
            ],
            [
                'category_id' => $categories['suplemen-vitamin'],
                'name' => 'Blackmores Pregnancy & Breastfeeding Gold',
                'slug' => 'blackmores-pregnancy-breastfeeding-gold',
                'description' => 'Suplemen lengkap untuk ibu hamil dan menyusui dengan asam folat, DHA, dan multivitamin.',
                'image' => 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=500&h=500&fit=crop',
                'sku' => 'VIT-005',
                'price' => 380000,
                'discount_price' => 349000,
                'stock' => 120,
                'unit' => 'botol',
                'brand' => 'Blackmores',
            ],
            [
                'category_id' => $categories['suplemen-vitamin'],
                'name' => 'Vitamin D3 1000 IU',
                'slug' => 'vitamin-d3-1000-iu',
                'description' => 'Vitamin D3 untuk kesehatan tulang, gigi, dan sistem imun, penting untuk penyerapan kalsium.',
                'image' => 'https://images.unsplash.com/photo-1550572017-edd951aa8cae?w=500&h=500&fit=crop',
                'sku' => 'VIT-006',
                'price' => 125000,
                'stock' => 160,
                'unit' => 'botol',
                'brand' => 'Wellness',
            ],
            [
                'category_id' => $categories['suplemen-vitamin'],
                'name' => 'Zinc 50mg Tablets',
                'slug' => 'zinc-50mg-tablets',
                'description' => 'Suplemen zinc untuk meningkatkan imunitas, kesehatan kulit, dan penyembuhan luka.',
                'image' => 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&h=500&fit=crop',
                'sku' => 'VIT-007',
                'price' => 85000,
                'stock' => 140,
                'unit' => 'botol',
                'brand' => 'Nature Made',
            ],
            [
                'category_id' => $categories['suplemen-vitamin'],
                'name' => 'Multivitamin Complete Formula',
                'slug' => 'multivitamin-complete-formula',
                'description' => 'Multivitamin lengkap dengan mineral untuk kesehatan tubuh secara menyeluruh.',
                'image' => 'https://images.unsplash.com/photo-1550572017-edd951aa8cae?w=500&h=500&fit=crop',
                'sku' => 'VIT-008',
                'price' => 165000,
                'stock' => 130,
                'unit' => 'botol',
                'brand' => 'Centrum',
            ],
            [
                'category_id' => $categories['suplemen-vitamin'],
                'name' => 'Calcium + D3 Tablets',
                'slug' => 'calcium-d3-tablets',
                'description' => 'Kalsium dengan vitamin D3 untuk kesehatan tulang dan gigi, mencegah osteoporosis.',
                'image' => 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&h=500&fit=crop',
                'sku' => 'VIT-009',
                'price' => 115000,
                'stock' => 150,
                'unit' => 'botol',
                'brand' => 'Wellness',
            ],
            [
                'category_id' => $categories['suplemen-vitamin'],
                'name' => 'Vitamin B Complex',
                'slug' => 'vitamin-b-complex',
                'description' => 'Vitamin B kompleks untuk energi, metabolisme, dan kesehatan sistem saraf.',
                'image' => 'https://images.unsplash.com/photo-1550572017-edd951aa8cae?w=500&h=500&fit=crop',
                'sku' => 'VIT-010',
                'price' => 95000,
                'stock' => 170,
                'unit' => 'botol',
                'brand' => 'Nature Made',
            ],
            [
                'category_id' => $categories['suplemen-vitamin'],
                'name' => 'Vitamin E 400 IU',
                'slug' => 'vitamin-e-400-iu',
                'description' => 'Vitamin E antioksidan untuk kesehatan kulit, rambut, dan mencegah penuaan dini.',
                'image' => 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&h=500&fit=crop',
                'sku' => 'VIT-011',
                'price' => 145000,
                'stock' => 110,
                'unit' => 'botol',
                'brand' => 'Blackmores',
            ],
            [
                'category_id' => $categories['suplemen-vitamin'],
                'name' => 'Collagen Peptides Powder',
                'slug' => 'collagen-peptides-powder',
                'description' => 'Collagen powder untuk kesehatan kulit, rambut, kuku, dan sendi, unflavored.',
                'image' => 'https://images.unsplash.com/photo-1608060434411-0a525d95e1d9?w=500&h=500&fit=crop',
                'sku' => 'VIT-012',
                'price' => 385000,
                'discount_price' => 349000,
                'stock' => 90,
                'unit' => 'pack',
                'brand' => 'Vital Proteins',
            ],

            // ALAT TERAPI (8 produk)
            [
                'category_id' => $categories['alat-terapi'],
                'name' => 'Kursi Roda Lipat Aluminium',
                'slug' => 'kursi-roda-lipat-aluminium',
                'description' => 'Kursi roda aluminium ringan dan lipat, kapasitas 120kg, roda 24 inch, rem tangan, footrest adjustable.',
                'image' => 'https://images.unsplash.com/photo-1581579186913-45ac3e6bbd13?w=500&h=500&fit=crop',
                'sku' => 'WHEEL-001',
                'price' => 1850000,
                'discount_price' => 1699000,
                'stock' => 25,
                'unit' => 'pcs',
                'brand' => 'GEA',
                'is_featured' => true,
            ],
            [
                'category_id' => $categories['alat-terapi'],
                'name' => 'Tongkat Kruk Ketiak Adjustable',
                'slug' => 'tongkat-kruk-ketiak-adjustable',
                'description' => 'Kruk/tongkat ketiak adjustable height, aluminium ringan, karet anti-slip, kapasitas 100kg.',
                'image' => 'https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?w=500&h=500&fit=crop',
                'sku' => 'CRUTCH-001',
                'price' => 185000,
                'stock' => 50,
                'unit' => 'pair',
                'brand' => 'OneMed',
            ],
            [
                'category_id' => $categories['alat-terapi'],
                'name' => 'Walker Alat Bantu Jalan Lipat',
                'slug' => 'walker-alat-bantu-jalan-lipat',
                'description' => 'Walker lipat untuk lansia dan rehabilitasi, ada roda depan, adjustable height, ringan.',
                'image' => 'https://images.unsplash.com/photo-1581579186913-45ac3e6bbd13?w=500&h=500&fit=crop',
                'sku' => 'WALKER-001',
                'price' => 385000,
                'stock' => 35,
                'unit' => 'pcs',
                'brand' => 'GEA',
            ],
            [
                'category_id' => $categories['alat-terapi'],
                'name' => 'Alat Terapi TENS (Transcutaneous Electrical Nerve Stimulation)',
                'slug' => 'alat-terapi-tens',
                'description' => 'TENS unit untuk terapi nyeri kronis, 8 mode, 20 level intensitas, 4 electrode pads, rechargeable.',
                'image' => 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=500&h=500&fit=crop',
                'sku' => 'TENS-001',
                'price' => 450000,
                'discount_price' => 399000,
                'stock' => 40,
                'unit' => 'pcs',
                'brand' => 'Beurer',
            ],
            [
                'category_id' => $categories['alat-terapi'],
                'name' => 'Bantal Terapi Cervical Pillow',
                'slug' => 'bantal-terapi-cervical-pillow',
                'description' => 'Bantal ortopedi untuk terapi leher, memory foam, ergonomic design, mengurangi nyeri leher.',
                'image' => 'https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?w=500&h=500&fit=crop',
                'sku' => 'PILLOW-001',
                'price' => 185000,
                'stock' => 60,
                'unit' => 'pcs',
                'brand' => 'Tempur',
            ],
            [
                'category_id' => $categories['alat-terapi'],
                'name' => 'Korset Penyangga Pinggang Lumbar Support',
                'slug' => 'korset-penyangga-pinggang-lumbar-support',
                'description' => 'Korset lumbar untuk support punggung bawah, mengurangi nyeri, breathable material, adjustable.',
                'image' => 'https://images.unsplash.com/photo-1578679414271-150d0cd5c52d?w=500&h=500&fit=crop',
                'sku' => 'LUMBAR-001',
                'price' => 165000,
                'stock' => 80,
                'unit' => 'pcs',
                'brand' => 'LP Support',
            ],
            [
                'category_id' => $categories['alat-terapi'],
                'name' => 'Ankle Support Penyangga Pergelangan Kaki',
                'slug' => 'ankle-support-penyangga-pergelangan-kaki',
                'description' => 'Ankle brace untuk support dan recovery cedera pergelangan kaki, compression, adjustable strap.',
                'image' => 'https://images.unsplash.com/photo-1578679414271-150d0cd5c52d?w=500&h=500&fit=crop',
                'sku' => 'ANKLE-001',
                'price' => 95000,
                'stock' => 100,
                'unit' => 'pcs',
                'brand' => 'LP Support',
            ],
            [
                'category_id' => $categories['alat-terapi'],
                'name' => 'Knee Support Penyangga Lutut',
                'slug' => 'knee-support-penyangga-lutut',
                'description' => 'Knee brace dengan spring support, untuk cedera ligamen, arthritis, olahraga, breathable.',
                'image' => 'https://images.unsplash.com/photo-1578679414271-150d0cd5c52d?w=500&h=500&fit=crop',
                'sku' => 'KNEE-001',
                'price' => 125000,
                'stock' => 90,
                'unit' => 'pcs',
                'brand' => 'LP Support',
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}


