<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Dapatkan kategori yang sudah ada
        $categories = Category::all()->pluck('id', 'slug');

        $products = [
            // OBAT RESEP (15 produk) - Setiap gambar berbeda
            [
                'category_id' => $categories['obat-resep'],
                'name' => 'Amoxicillin 500mg (Strip 10 Tablet)',
                'slug' => 'amoxicillin-500mg-strip-10-tablet',
                'description' => 'Antibiotik untuk infeksi bakteri seperti infeksi saluran pernapasan, infeksi kulit, dan infeksi telinga.',
                'image' => 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=500&h=500&fit=crop&q=80&auto=format',
                'sku' => 'RX-001',
                'price' => 15000,
                'stock' => 200,
                'unit' => 'strip',
                'brand' => 'Kimia Farma',
                'is_featured' => true,
            ],
            [
                'category_id' => $categories['obat-resep'],
                'name' => 'Metformin 500mg (Strip 10 Tablet)',
                'slug' => 'metformin-500mg-strip-10-tablet',
                'description' => 'Obat antidiabetes untuk mengontrol kadar gula darah pada pasien diabetes tipe 2.',
                'image' => 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&h=500&fit=crop&q=80&auto=format',
                'sku' => 'RX-002',
                'price' => 12000,
                'stock' => 180,
                'unit' => 'strip',
                'brand' => 'Dexa Medica',
                'is_featured' => true,
            ],
            [
                'category_id' => $categories['obat-resep'],
                'name' => 'Amlodipine 10mg (Strip 10 Tablet)',
                'slug' => 'amlodipine-10mg-strip-10-tablet',
                'description' => 'Obat antihipertensi untuk menurunkan tekanan darah tinggi dan mencegah komplikasi jantung.',
                'image' => 'https://images.unsplash.com/photo-1550572017-edd951aa8cae?w=500&h=500&fit=crop&q=80&auto=format',
                'sku' => 'RX-003',
                'price' => 18000,
                'stock' => 150,
                'unit' => 'strip',
                'brand' => 'Kalbe Farma',
            ],
            [
                'category_id' => $categories['obat-resep'],
                'name' => 'Omeprazole 20mg (Strip 10 Kapsul)',
                'slug' => 'omeprazole-20mg-strip-10-kapsul',
                'description' => 'Obat untuk mengurangi asam lambung, mengobati GERD, tukak lambung, dan tukak duodenum.',
                'image' => 'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=500&h=500&fit=crop&q=80&auto=format',
                'sku' => 'RX-004',
                'price' => 25000,
                'stock' => 160,
                'unit' => 'strip',
                'brand' => 'Sanbe Farma',
            ],
            [
                'category_id' => $categories['obat-resep'],
                'name' => 'Simvastatin 20mg (Strip 10 Tablet)',
                'slug' => 'simvastatin-20mg-strip-10-tablet',
                'description' => 'Obat untuk menurunkan kolesterol dan mencegah penyakit jantung koroner.',
                'image' => 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=500&h=500&fit=crop&q=80&auto=format',
                'sku' => 'RX-005',
                'price' => 22000,
                'stock' => 140,
                'unit' => 'strip',
                'brand' => 'Novell Pharmaceutical',
            ],
            [
                'category_id' => $categories['obat-resep'],
                'name' => 'Ciprofloxacin 500mg (Strip 10 Tablet)',
                'slug' => 'ciprofloxacin-500mg-strip-10-tablet',
                'description' => 'Antibiotik fluoroquinolone untuk infeksi saluran kemih, infeksi saluran pencernaan.',
                'image' => 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=500&h=500&fit=crop&q=80&auto=format',
                'sku' => 'RX-006',
                'price' => 28000,
                'stock' => 120,
                'unit' => 'strip',
                'brand' => 'Kimia Farma',
            ],
            [
                'category_id' => $categories['obat-resep'],
                'name' => 'Losartan 50mg (Strip 10 Tablet)',
                'slug' => 'losartan-50mg-strip-10-tablet',
                'description' => 'Obat antihipertensi golongan ARB untuk menurunkan tekanan darah tinggi.',
                'image' => 'https://images.unsplash.com/photo-1603883359806-e84a4f285f93?w=500&h=500&fit=crop&q=80&auto=format',
                'sku' => 'RX-007',
                'price' => 20000,
                'stock' => 130,
                'unit' => 'strip',
                'brand' => 'Dexa Medica',
            ],
            [
                'category_id' => $categories['obat-resep'],
                'name' => 'Atorvastatin 20mg (Strip 10 Tablet)',
                'slug' => 'atorvastatin-20mg-strip-10-tablet',
                'description' => 'Obat penurun kolesterol untuk mencegah penyakit kardiovaskular.',
                'image' => 'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=500&h=500&fit=crop&q=80&auto=format',
                'sku' => 'RX-008',
                'price' => 32000,
                'stock' => 110,
                'unit' => 'strip',
                'brand' => 'Kalbe Farma',
            ],
            [
                'category_id' => $categories['obat-resep'],
                'name' => 'Clopidogrel 75mg (Strip 10 Tablet)',
                'slug' => 'clopidogrel-75mg-strip-10-tablet',
                'description' => 'Obat antiplatelet untuk mencegah pembekuan darah dan stroke.',
                'image' => 'https://images.unsplash.com/photo-1615461066841-6116e61058f4?w=500&h=500&fit=crop&q=80&auto=format',
                'sku' => 'RX-009',
                'price' => 45000,
                'stock' => 100,
                'unit' => 'strip',
                'brand' => 'Sanbe Farma',
            ],
            [
                'category_id' => $categories['obat-resep'],
                'name' => 'Levothyroxine 100mcg (Strip 10 Tablet)',
                'slug' => 'levothyroxine-100mcg-strip-10-tablet',
                'description' => 'Hormon tiroid sintetik untuk mengobati hipotiroidisme.',
                'image' => 'https://images.unsplash.com/photo-1631815589968-fdb09a223b1e?w=500&h=500&fit=crop&q=80&auto=format',
                'sku' => 'RX-010',
                'price' => 35000,
                'stock' => 90,
                'unit' => 'strip',
                'brand' => 'Merck',
            ],
            [
                'category_id' => $categories['obat-resep'],
                'name' => 'Glimepiride 2mg (Strip 10 Tablet)',
                'slug' => 'glimepiride-2mg-strip-10-tablet',
                'description' => 'Obat antidiabetes oral untuk mengontrol gula darah diabetes tipe 2.',
                'image' => 'https://images.unsplash.com/photo-1584820927498-cfe5211fd8bf?w=500&h=500&fit=crop&q=80&auto=format',
                'sku' => 'RX-011',
                'price' => 16000,
                'stock' => 150,
                'unit' => 'strip',
                'brand' => 'Dexa Medica',
            ],
            [
                'category_id' => $categories['obat-resep'],
                'name' => 'Captopril 25mg (Strip 10 Tablet)',
                'slug' => 'captopril-25mg-strip-10-tablet',
                'description' => 'Obat ACE inhibitor untuk hipertensi dan gagal jantung.',
                'image' => 'https://images.unsplash.com/photo-1603796846097-bee99e4a601f?w=500&h=500&fit=crop&q=80&auto=format',
                'sku' => 'RX-012',
                'price' => 8000,
                'stock' => 200,
                'unit' => 'strip',
                'brand' => 'Kimia Farma',
            ],
            [
                'category_id' => $categories['obat-resep'],
                'name' => 'Ranitidine 150mg (Strip 10 Tablet)',
                'slug' => 'ranitidine-150mg-strip-10-tablet',
                'description' => 'Obat untuk mengurangi produksi asam lambung dan mengobati tukak lambung.',
                'image' => 'https://images.unsplash.com/photo-1584744982493-457e7a46d0d4?w=500&h=500&fit=crop&q=80&auto=format',
                'sku' => 'RX-013',
                'price' => 12000,
                'stock' => 170,
                'unit' => 'strip',
                'brand' => 'Sanbe Farma',
            ],
            [
                'category_id' => $categories['obat-resep'],
                'name' => 'Bisoprolol 5mg (Strip 10 Tablet)',
                'slug' => 'bisoprolol-5mg-strip-10-tablet',
                'description' => 'Beta blocker untuk hipertensi dan penyakit jantung koroner.',
                'image' => 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=500&h=500&fit=crop&q=80&auto=format',
                'sku' => 'RX-014',
                'price' => 24000,
                'stock' => 120,
                'unit' => 'strip',
                'brand' => 'Kalbe Farma',
            ],
            [
                'category_id' => $categories['obat-resep'],
                'name' => 'Allopurinol 300mg (Strip 10 Tablet)',
                'slug' => 'allopurinol-300mg-strip-10-tablet',
                'description' => 'Obat untuk menurunkan kadar asam urat dan mencegah serangan asam urat.',
                'image' => 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=500&h=500&fit=crop&q=80&auto=format',
                'sku' => 'RX-015',
                'price' => 14000,
                'stock' => 140,
                'unit' => 'strip',
                'brand' => 'Novell Pharmaceutical',
            ],

            // OBAT BEBAS (15 produk) - Setiap gambar berbeda
            [
                'category_id' => $categories['obat-bebas'],
                'name' => 'Paracetamol 500mg (Strip 10 Tablet)',
                'slug' => 'paracetamol-500mg-strip-10-tablet',
                'description' => 'Obat pereda nyeri dan penurun demam untuk sakit kepala, demam, dan nyeri ringan hingga sedang.',
                'image' => 'https://images.unsplash.com/photo-1628771065518-0d82f1938462?w=500&h=500&fit=crop&q=80&auto=format',
                'sku' => 'OTC-001',
                'price' => 5000,
                'stock' => 300,
                'unit' => 'strip',
                'brand' => 'Kimia Farma',
                'is_featured' => true,
            ],
            [
                'category_id' => $categories['obat-bebas'],
                'name' => 'Bodrex Tablet (Strip 4 Tablet)',
                'slug' => 'bodrex-tablet-strip-4-tablet',
                'description' => 'Obat sakit kepala dengan kombinasi paracetamol, kafein, dan propyphenazone.',
                'image' => 'https://images.unsplash.com/photo-1563213126-a4273aed2016?w=500&h=500&fit=crop&q=80&auto=format',
                'sku' => 'OTC-002',
                'price' => 3500,
                'stock' => 400,
                'unit' => 'strip',
                'brand' => 'Tempo Scan Pacific',
                'is_featured' => true,
            ],
            [
                'category_id' => $categories['obat-bebas'],
                'name' => 'Promag Tablet (Strip 10 Tablet)',
                'slug' => 'promag-tablet-strip-10-tablet',
                'description' => 'Obat maag untuk meredakan gejala sakit maag, kembung, dan mual.',
                'image' => 'https://images.unsplash.com/photo-1587049352846-4a222e784338?w=500&h=500&fit=crop&q=80&auto=format',
                'sku' => 'OTC-003',
                'price' => 8000,
                'stock' => 250,
                'unit' => 'strip',
                'brand' => 'Kalbe Farma',
                'is_featured' => true,
            ],
            [
                'category_id' => $categories['obat-bebas'],
                'name' => 'Antangin JRG Cair (1 Sachet)',
                'slug' => 'antangin-jrg-cair-1-sachet',
                'description' => 'Obat herbal cair untuk masuk angin, perut kembung, mual, dan pusing.',
                'image' => 'https://images.unsplash.com/photo-1608060434411-0a525d95e1d9?w=500&h=500&fit=crop&q=80&auto=format',
                'sku' => 'OTC-004',
                'price' => 3000,
                'stock' => 500,
                'unit' => 'sachet',
                'brand' => 'Deltomed',
            ],
            [
                'category_id' => $categories['obat-bebas'],
                'name' => 'OBH Combi Batuk Sirup 100ml',
                'slug' => 'obh-combi-batuk-sirup-100ml',
                'description' => 'Sirup obat batuk untuk meredakan batuk berdahak dan tidak berdahak.',
                'image' => 'https://images.unsplash.com/photo-1631815589968-fdb09a223b1e?w=500&h=500&fit=crop&q=80&auto=format&sat=-100&hue=20',
                'sku' => 'OTC-005',
                'price' => 18000,
                'discount_price' => 16000,
                'stock' => 200,
                'unit' => 'botol',
                'brand' => 'Combiphar',
            ],
            [
                'category_id' => $categories['obat-bebas'],
                'name' => 'Procold Flu & Batuk (Strip 4 Tablet)',
                'slug' => 'procold-flu-batuk-strip-4-tablet',
                'description' => 'Obat untuk meredakan gejala flu seperti demam, sakit kepala, hidung tersumbat, dan batuk.',
                'image' => 'https://images.unsplash.com/photo-1550576321-8c6b8fb3e6c2?w=500&h=500&fit=crop&q=80&auto=format',
                'sku' => 'OTC-006',
                'price' => 7000,
                'stock' => 280,
                'unit' => 'strip',
                'brand' => 'Dexa Medica',
            ],
            [
                'category_id' => $categories['obat-bebas'],
                'name' => 'Mylanta Tablet (Strip 10 Tablet)',
                'slug' => 'mylanta-tablet-strip-10-tablet',
                'description' => 'Obat antasida untuk mengatasi gejala sakit maag, kembung, dan nyeri ulu hati.',
                'image' => 'https://images.unsplash.com/photo-1574258495973-f010dfbb5371?w=500&h=500&fit=crop&q=80&auto=format',
                'sku' => 'OTC-007',
                'price' => 12000,
                'stock' => 220,
                'unit' => 'strip',
                'brand' => 'Johnson & Johnson',
            ],
            [
                'category_id' => $categories['obat-bebas'],
                'name' => 'Woods Peppermint Antitussive Sirup 60ml',
                'slug' => 'woods-peppermint-antitussive-sirup-60ml',
                'description' => 'Obat batuk dengan rasa peppermint untuk meredakan batuk dan tenggorokan gatal.',
                'image' => 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=500&h=500&fit=crop&q=80&auto=format&hue=180',
                'sku' => 'OTC-008',
                'price' => 15000,
                'stock' => 180,
                'unit' => 'botol',
                'brand' => 'Kalbe Farma',
            ],
            [
                'category_id' => $categories['obat-bebas'],
                'name' => 'Mixagrip Flu & Batuk (Strip 4 Tablet)',
                'slug' => 'mixagrip-flu-batuk-strip-4-tablet',
                'description' => 'Obat untuk meringankan gejala flu seperti demam, sakit kepala, hidung tersumbat.',
                'image' => 'https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?w=500&h=500&fit=crop&q=80&auto=format',
                'sku' => 'OTC-009',
                'price' => 6000,
                'stock' => 320,
                'unit' => 'strip',
                'brand' => 'Tempo Scan Pacific',
            ],
            [
                'category_id' => $categories['obat-bebas'],
                'name' => 'Diapet NR Kapsul (Strip 6 Kapsul)',
                'slug' => 'diapet-nr-kapsul-strip-6-kapsul',
                'description' => 'Obat diare untuk menghentikan diare dan meredakan mulas.',
                'image' => 'https://images.unsplash.com/photo-1581579186913-45ac3e6bbd13?w=500&h=500&fit=crop&q=80&auto=format',
                'sku' => 'OTC-010',
                'price' => 10000,
                'stock' => 200,
                'unit' => 'strip',
                'brand' => 'Soho Global Health',
            ],
            [
                'category_id' => $categories['obat-bebas'],
                'name' => 'Sangobion Kapsul (Strip 10 Kapsul)',
                'slug' => 'sangobion-kapsul-strip-10-kapsul',
                'description' => 'Suplemen zat besi untuk mengatasi dan mencegah anemia.',
                'image' => 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=500&h=500&fit=crop&q=80&auto=format&hue=340',
                'sku' => 'OTC-011',
                'price' => 15000,
                'stock' => 180,
                'unit' => 'strip',
                'brand' => 'Merck',
            ],
            [
                'category_id' => $categories['obat-bebas'],
                'name' => 'Tolak Angin Cair (1 Sachet)',
                'slug' => 'tolak-angin-cair-1-sachet',
                'description' => 'Jamu cair untuk masuk angin, perut kembung, mual, dan pusing.',
                'image' => 'https://images.unsplash.com/photo-1512069772995-ec65ed45afd6?w=500&h=500&fit=crop&q=80&auto=format',
                'sku' => 'OTC-012',
                'price' => 2500,
                'stock' => 600,
                'unit' => 'sachet',
                'brand' => 'Sido Muncul',
            ],
            [
                'category_id' => $categories['obat-bebas'],
                'name' => 'Neo Rheumacyl Tablet (Strip 10 Tablet)',
                'slug' => 'neo-rheumacyl-tablet-strip-10-tablet',
                'description' => 'Obat untuk meredakan nyeri otot, pegal linu, dan sakit pinggang.',
                'image' => 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=500&h=500&fit=crop&q=80&auto=format',
                'sku' => 'OTC-013',
                'price' => 9000,
                'stock' => 240,
                'unit' => 'strip',
                'brand' => 'Tempo Scan Pacific',
            ],
            [
                'category_id' => $categories['obat-bebas'],
                'name' => 'Insto Dry Eyes Tetes Mata 7.5ml',
                'slug' => 'insto-dry-eyes-tetes-mata-75ml',
                'description' => 'Obat tetes mata untuk meredakan mata kering, merah, dan iritasi.',
                'image' => 'https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?w=500&h=500&fit=crop&q=80&auto=format',
                'sku' => 'OTC-014',
                'price' => 22000,
                'stock' => 150,
                'unit' => 'botol',
                'brand' => 'Combiphar',
            ],
            [
                'category_id' => $categories['obat-bebas'],
                'name' => 'Feminax Tablet (Strip 10 Tablet)',
                'slug' => 'feminax-tablet-strip-10-tablet',
                'description' => 'Obat untuk meredakan nyeri haid dan kram perut saat menstruasi.',
                'image' => 'https://images.unsplash.com/photo-1578679414271-150d0cd5c52d?w=500&h=500&fit=crop&q=80&auto=format',
                'sku' => 'OTC-015',
                'price' => 11000,
                'stock' => 160,
                'unit' => 'strip',
                'brand' => 'Konimex',
            ],

            // SUPLEMEN & VITAMIN (12 produk) - Setiap gambar berbeda
            [
                'category_id' => $categories['suplemen-vitamin'],
                'name' => 'Blackmores Vitamin C 1000mg (150 tablets)',
                'slug' => 'blackmores-vitamin-c-1000mg-150-tablets',
                'description' => 'Vitamin C dosis tinggi untuk meningkatkan daya tahan tubuh, antioksidan kuat.',
                'image' => 'https://images.unsplash.com/photo-1550572017-edd951aa8cae?w=500&h=500&fit=crop&q=80&auto=format&hue=30',
                'sku' => 'VIT-001',
                'price' => 285000,
                'discount_price' => 259000,
                'stock' => 180,
                'unit' => 'botol',
                'brand' => 'Blackmores',
                'is_featured' => true,
            ],
            [
                'category_id' => $categories['suplemen-vitamin'],
                'name' => 'Blackmores Omega 3 Fish Oil 1000mg',
                'slug' => 'blackmores-omega-3-fish-oil-1000mg',
                'description' => 'Omega 3 dari minyak ikan untuk kesehatan jantung, otak, dan mata.',
                'image' => 'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=500&h=500&fit=crop&q=80&auto=format&hue=200',
                'sku' => 'VIT-002',
                'price' => 320000,
                'discount_price' => 289000,
                'stock' => 150,
                'unit' => 'botol',
                'brand' => 'Blackmores',
                'is_featured' => true,
            ],
            [
                'category_id' => $categories['suplemen-vitamin'],
                'name' => 'Wellness Excell-C 500mg',
                'slug' => 'wellness-excell-c-500mg',
                'description' => 'Vitamin C 500mg dengan bioflavonoid untuk meningkatkan imunitas.',
                'image' => 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&h=500&fit=crop&q=80&auto=format&hue=50',
                'sku' => 'VIT-003',
                'price' => 95000,
                'stock' => 200,
                'unit' => 'botol',
                'brand' => 'Wellness',
            ],
            [
                'category_id' => $categories['suplemen-vitamin'],
                'name' => 'Vitamin D3 1000 IU',
                'slug' => 'vitamin-d3-1000-iu',
                'description' => 'Vitamin D3 untuk kesehatan tulang, gigi, dan sistem imun.',
                'image' => 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=500&h=500&fit=crop&q=80&auto=format&hue=60',
                'sku' => 'VIT-004',
                'price' => 125000,
                'stock' => 160,
                'unit' => 'botol',
                'brand' => 'Wellness',
            ],
            [
                'category_id' => $categories['suplemen-vitamin'],
                'name' => 'Zinc 50mg Tablets',
                'slug' => 'zinc-50mg-tablets',
                'description' => 'Suplemen zinc untuk meningkatkan imunitas dan kesehatan kulit.',
                'image' => 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=500&h=500&fit=crop&q=80&auto=format&hue=180',
                'sku' => 'VIT-005',
                'price' => 85000,
                'stock' => 140,
                'unit' => 'botol',
                'brand' => 'Nature Made',
            ],
            [
                'category_id' => $categories['suplemen-vitamin'],
                'name' => 'Multivitamin Complete Formula',
                'slug' => 'multivitamin-complete-formula',
                'description' => 'Multivitamin lengkap dengan mineral untuk kesehatan tubuh.',
                'image' => 'https://images.unsplash.com/photo-1615461066841-6116e61058f4?w=500&h=500&fit=crop&q=80&auto=format&hue=270',
                'sku' => 'VIT-006',
                'price' => 165000,
                'stock' => 130,
                'unit' => 'botol',
                'brand' => 'Centrum',
            ],
            [
                'category_id' => $categories['suplemen-vitamin'],
                'name' => 'Calcium + D3 Tablets',
                'slug' => 'calcium-d3-tablets',
                'description' => 'Kalsium dengan vitamin D3 untuk kesehatan tulang dan gigi.',
                'image' => 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=500&h=500&fit=crop&q=80&auto=format&hue=210',
                'sku' => 'VIT-007',
                'price' => 115000,
                'stock' => 150,
                'unit' => 'botol',
                'brand' => 'Wellness',
            ],
            [
                'category_id' => $categories['suplemen-vitamin'],
                'name' => 'Vitamin B Complex',
                'slug' => 'vitamin-b-complex',
                'description' => 'Vitamin B kompleks untuk energi, metabolisme, dan kesehatan sistem saraf.',
                'image' => 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=500&h=500&fit=crop&q=80&auto=format&hue=40',
                'sku' => 'VIT-008',
                'price' => 95000,
                'stock' => 170,
                'unit' => 'botol',
                'brand' => 'Nature Made',
            ],
            [
                'category_id' => $categories['suplemen-vitamin'],
                'name' => 'Vitamin E 400 IU',
                'slug' => 'vitamin-e-400-iu',
                'description' => 'Vitamin E antioksidan untuk kesehatan kulit dan rambut.',
                'image' => 'https://images.unsplash.com/photo-1603883359806-e84a4f285f93?w=500&h=500&fit=crop&q=80&auto=format&hue=330',
                'sku' => 'VIT-009',
                'price' => 145000,
                'stock' => 110,
                'unit' => 'botol',
                'brand' => 'Blackmores',
            ],
            [
                'category_id' => $categories['suplemen-vitamin'],
                'name' => 'Collagen Peptides Powder',
                'slug' => 'collagen-peptides-powder',
                'description' => 'Collagen powder untuk kesehatan kulit, rambut, kuku, dan sendi.',
                'image' => 'https://images.unsplash.com/photo-1608060434411-0a525d95e1d9?w=500&h=500&fit=crop&q=80&auto=format&hue=340',
                'sku' => 'VIT-010',
                'price' => 385000,
                'discount_price' => 349000,
                'stock' => 90,
                'unit' => 'pack',
                'brand' => 'Vital Proteins',
            ],
            [
                'category_id' => $categories['suplemen-vitamin'],
                'name' => 'Probiotics 10 Billion CFU',
                'slug' => 'probiotics-10-billion-cfu',
                'description' => 'Suplemen probiotik untuk kesehatan pencernaan dan sistem imun.',
                'image' => 'https://images.unsplash.com/photo-1631815589968-fdb09a223b1e?w=500&h=500&fit=crop&q=80&auto=format&hue=120',
                'sku' => 'VIT-011',
                'price' => 195000,
                'stock' => 120,
                'unit' => 'botol',
                'brand' => 'Nature Made',
            ],
            [
                'category_id' => $categories['suplemen-vitamin'],
                'name' => 'Biotin 10000mcg Hair & Skin',
                'slug' => 'biotin-10000mcg-hair-skin',
                'description' => 'Biotin dosis tinggi untuk kesehatan rambut, kulit, dan kuku.',
                'image' => 'https://images.unsplash.com/photo-1584820927498-cfe5211fd8bf?w=500&h=500&fit=crop&q=80&auto=format&hue=300',
                'sku' => 'VIT-012',
                'price' => 175000,
                'stock' => 100,
                'unit' => 'botol',
                'brand' => 'Nature\'s Bounty',
            ],

            // OBAT HERBAL (8 produk) - Setiap gambar berbeda
            [
                'category_id' => $categories['obat-herbal'],
                'name' => 'Herbadrink Sari Jahe (Box 5 Sachet)',
                'slug' => 'herbadrink-sari-jahe-box-5-sachet',
                'description' => 'Minuman herbal sari jahe untuk menghangatkan tubuh dan meredakan masuk angin.',
                'image' => 'https://images.unsplash.com/photo-1556228852-80a9060e5462?w=500&h=500&fit=crop&q=80&auto=format',
                'sku' => 'HRB-001',
                'price' => 15000,
                'stock' => 200,
                'unit' => 'box',
                'brand' => 'Konimex',
            ],
            [
                'category_id' => $categories['obat-herbal'],
                'name' => 'Tolak Angin Cair Box (12 Sachet)',
                'slug' => 'tolak-angin-cair-box-12-sachet',
                'description' => 'Jamu herbal cair untuk masuk angin, perut kembung, mual, dan pusing.',
                'image' => 'https://images.unsplash.com/photo-1608060434411-0a525d95e1d9?w=500&h=500&fit=crop&q=80&auto=format&sat=20',
                'sku' => 'HRB-002',
                'price' => 28000,
                'discount_price' => 25000,
                'stock' => 250,
                'unit' => 'box',
                'brand' => 'Sido Muncul',
                'is_featured' => true,
            ],
            [
                'category_id' => $categories['obat-herbal'],
                'name' => 'Kunyit Asam Sido Muncul (Box 5 Sachet)',
                'slug' => 'kunyit-asam-sido-muncul-box-5-sachet',
                'description' => 'Jamu tradisional kunyit asam untuk kesehatan wanita dan melancarkan haid.',
                'image' => 'https://images.unsplash.com/photo-1512069772995-ec65ed45afd6?w=500&h=500&fit=crop&q=80&auto=format&hue=50',
                'sku' => 'HRB-003',
                'price' => 12000,
                'stock' => 180,
                'unit' => 'box',
                'brand' => 'Sido Muncul',
            ],
            [
                'category_id' => $categories['obat-herbal'],
                'name' => 'Madurasa Madu Murni 150gr',
                'slug' => 'madurasa-madu-murni-150gr',
                'description' => 'Madu murni untuk meningkatkan daya tahan tubuh dan kesehatan.',
                'image' => 'https://images.unsplash.com/photo-1587049352846-4a222e784338?w=500&h=500&fit=crop&q=80&auto=format&hue=40',
                'sku' => 'HRB-004',
                'price' => 35000,
                'stock' => 150,
                'unit' => 'botol',
                'brand' => 'Air Mancur',
            ],
            [
                'category_id' => $categories['obat-herbal'],
                'name' => 'Minyak Kayu Putih Cap Lang 60ml',
                'slug' => 'minyak-kayu-putih-cap-lang-60ml',
                'description' => 'Minyak kayu putih aromaterapi untuk meredakan masuk angin dan pegal linu.',
                'image' => 'https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=500&h=500&fit=crop&q=80&auto=format',
                'sku' => 'HRB-005',
                'price' => 18000,
                'stock' => 220,
                'unit' => 'botol',
                'brand' => 'Cap Lang',
            ],
            [
                'category_id' => $categories['obat-herbal'],
                'name' => 'Antis Balsem 20gr',
                'slug' => 'antis-balsem-20gr',
                'description' => 'Balsem herbal untuk meredakan pegal linu, sakit kepala, dan masuk angin.',
                'image' => 'https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?w=500&h=500&fit=crop&q=80&auto=format&hue=120',
                'sku' => 'HRB-006',
                'price' => 12000,
                'stock' => 250,
                'unit' => 'pcs',
                'brand' => 'Antis',
            ],
            [
                'category_id' => $categories['obat-herbal'],
                'name' => 'Habbatussauda Oil 200 Kapsul',
                'slug' => 'habbatussauda-oil-200-kapsul',
                'description' => 'Minyak habbatussauda untuk meningkatkan imunitas dan kesehatan tubuh.',
                'image' => 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=500&h=500&fit=crop&q=80&auto=format&hue=200',
                'sku' => 'HRB-007',
                'price' => 85000,
                'discount_price' => 75000,
                'stock' => 120,
                'unit' => 'botol',
                'brand' => 'Kurma Ajwa',
            ],
            [
                'category_id' => $categories['obat-herbal'],
                'name' => 'Propolis Brazilian 10ml',
                'slug' => 'propolis-brazilian-10ml',
                'description' => 'Propolis Brazilian untuk meningkatkan daya tahan tubuh dan antibakteri alami.',
                'image' => 'https://images.unsplash.com/photo-1578679414271-150d0cd5c52d?w=500&h=500&fit=crop&q=80&auto=format&hue=45',
                'sku' => 'HRB-008',
                'price' => 125000,
                'stock' => 100,
                'unit' => 'botol',
                'brand' => 'Goodfit',
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
